#!/bin/sh
pkill -2 recorder
cd /home/wladcoat/trunk-recorder2/
mv trunk1.log /home/wladcoat/logs/trunk1_`date +%F-%H%M%S`.log
mv trunk2.log /home/wladcoat/logs/trunk2_`date +%F-%H%M%S`.log
nohup ./recorder > trunk1.log 2>trunk2.log &

